import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { NextResponse } from "next/server";

/**
 * POST /api/academy/seed — Admin-only. Seeds courses with content.
 */
export async function POST() {
  const session = await getSession();
  if (!session || session.user.role !== "ADMIN") {
    return NextResponse.json({ error: "Admin only" }, { status: 403 });
  }

  // Check if already seeded
  const existing = await db.course.count();
  if (existing > 0) return NextResponse.json({ message: `${existing} courses already exist. Delete first to re-seed.` });

  const courses = [
    /* ═══════════════════ COURSE 1: Getting Started ═══════════════════ */
    {
      title: "Getting Started as a CouthActs Provider",
      slug: "getting-started-provider",
      description: "Learn how the CouthActs platform works, set up your provider profile, get verified, and land your first jobs.",
      whatYouLearn: ["How the platform connects providers and customers", "Setting up a profile that wins jobs", "KYC and KYB verification process", "Understanding the CouthActs Score", "Bidding strategy for new providers", "Getting paid through escrow"],
      category: "PLATFORM_MASTERY" as const, priceUsd: 49, duration: "2 hours", totalLessons: 8, level: "BEGINNER" as const,
      thumbnailUrl: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=600&q=80",
      lessons: [
        { title: "Welcome to CouthActs — How the Platform Works", order: 1, durationMins: 15, content: "CouthActs is a global transportation infrastructure platform that connects customers who need to move people or goods with verified transportation providers. Unlike traditional freight brokers or ride-hailing apps, CouthActs supports 18 different transport modes — from taxi rides and courier deliveries to cargo ships and private jets.\n\nThe platform operates on a simple cycle: customers post transportation needs, verified providers bid on those jobs, the customer selects a provider, funds are held in escrow, the job is completed with real-time tracking, and payment is released upon mutual confirmation.\n\nEvery transaction on CouthActs is escrow-protected. When a customer posts a job, their budget is held in their CouthActs Wallet. When they accept your bid, those funds are locked in escrow. You only get paid when both you and the customer confirm the job is complete. This protects both parties — the customer knows their money is safe, and you know the funds are already committed.\n\nAs a provider, your reputation is measured by your CouthActs Score — a 0-100 rating that considers your completion rate, on-time delivery, customer reviews, response time, and dispute history. A higher score means more trust, more bid acceptances, and access to premium features like CouthActs Advance.\n\nThe platform charges a sliding escrow fee (1-8% depending on job value) which is deducted from your payout on completion. There are no upfront fees to bid on jobs. Your earnings go directly to your CouthActs Wallet, and you can withdraw to your bank account via Stripe Connect at any time." },
        { title: "Setting Up Your Provider Profile for Maximum Visibility", order: 2, durationMins: 15, content: "Your provider profile is your storefront on CouthActs. Customers see it before they accept your bid. A complete, professional profile dramatically increases your bid acceptance rate.\n\nStart with your business name. If you're a solopreneur (taxi, limo, courier, or medical transport), your business name is automatically set to your personal name. For all other modes, you'll need a registered business name with proper documentation.\n\nSelect your transport modes carefully. Only choose modes you're actually equipped and licensed to serve. A freight trucking company shouldn't select yacht charter. The platform uses your registered modes to show you relevant jobs — selecting modes you can't serve wastes everyone's time and damages your score.\n\nYour bio should be concise and professional. Lead with your experience: 'Licensed FMCSA carrier with 12 years of cross-country freight experience. 48-foot flatbed fleet specializing in construction materials.' Customers want competence, not marketing fluff.\n\nAdd your service areas — the regions where you operate. Be specific: 'Northeast US (NY, NJ, CT, PA, MA)' is better than 'United States.' Upload fleet photos if you have them — real photos of your actual vehicles, not stock images. This builds trust instantly.\n\nList your certifications: HAZMAT endorsement, TWIC card, TSA-approved, ISO certifications, protection coverage levels. Every certification you add makes your profile more credible and opens you to jobs that require those qualifications." },
        { title: "Getting Verified — KYC and KYB Explained", order: 3, durationMins: 15, content: "Identity verification is mandatory on CouthActs. You cannot bid on any job until your identity is verified. This protects both you and your customers.\n\nKYC (Know Your Customer) is personal identity verification. Every user — customer or provider — must complete KYC before accessing platform features. The process uses Persona, a government-grade identity verification service. You'll upload a photo of your government-issued ID (passport, driver's license, or national ID) and take a selfie. Persona verifies that the ID is authentic, not expired, and that the selfie matches the ID photo.\n\nCritical requirement: the first and last name on your CouthActs account must exactly match the name on your government ID. If there's a mismatch, verification will be rejected. The $20 verification fee is non-refundable regardless of outcome, so make sure your name is correct before submitting.\n\nKYB (Know Your Business) is required for non-solopreneur providers. After completing KYC, you'll need to submit your business documentation: business license, protection certificate, and any mode-specific registrations (DOT number for trucking, IMO number for maritime, FAA certificates for aviation, etc.).\n\nThe CouthActs team manually reviews business documents within 1-3 business days. Once approved, your profile shows a 'KYB Verified' badge, which significantly increases customer trust in your bids.\n\nIf you change your name on CouthActs, your verification resets and you'll need to reverify ($20 again). This prevents identity fraud." },
        { title: "Understanding the CouthActs Score", order: 4, durationMins: 15, content: "Your CouthActs Score is the single most important number on your profile. It determines your tier (Elite, Trusted, Established, or Probation), affects how customers perceive your bids, and gates access to features like CouthActs Advance.\n\nThe score is calculated on a 100-point scale with seven factors:\n\n1. Completion Rate (25 points): What percentage of accepted bookings do you complete? Cancellations hurt this metric. If you accept a job, complete it.\n\n2. On-Time Rate (20 points): Of completed jobs with a delivery deadline, what percentage arrived on or before the deadline? Late deliveries reduce this score.\n\n3. Review Average (20 points): Your average customer rating out of 5 stars, scaled to 20 points. A 4.5/5 average gives you 18/20 points.\n\n4. Response Time (10 points): How quickly do you respond to job opportunities? Under 1 hour = full points. Over 24 hours = zero points.\n\n5. Dispute Penalty (-5 per dispute, max -15): Each dispute filed against you in the last 12 months costs 5 points. Three or more disputes deducts the maximum 15 points.\n\n6. Account Age (max 10 points): 1 point per month you've been on the platform, up to 10 points. Longevity builds trust.\n\n7. Verification Bonus (15 points): Being fully verified (KYC + KYB approved) adds 15 points.\n\nTier thresholds: 90-100 = Elite (gold), 75-89 = Trusted (silver), 60-74 = Established (gray), below 60 = Probation (red).\n\nYour score recalculates after every completed job. Focus on completing jobs, delivering on time, and communicating well — the score follows naturally." },
        { title: "How to Find and Bid on Jobs", order: 5, durationMins: 15, content: "Jobs on CouthActs come to you in two ways: the Browse Jobs page and Instant Jobs.\n\nThe Browse Jobs page shows all open postings that match your registered transport modes. If you're registered for FREIGHT_TRUCKING and HEAVY_HAUL, you'll only see freight and heavy haul jobs. You won't see taxi requests or yacht charters. This ensures every job you see is relevant to your capabilities.\n\nFor freight and cargo providers, the Load Board is your primary tool. It filters specifically for trucking, heavy haul, hazmat, oversized, rail, air cargo, and ocean freight. You can filter by mode, sort by budget or pickup date, and toggle for hazmat-only or fresh-in-the-last-24-hours jobs.\n\nWhen you find a job you want, click it to see full details: route, cargo specs, dates, insurance requirements, and the customer's budget range. Then click 'Place Bid' in the sidebar.\n\nYour bid should include: your price (in USD — the platform handles currency conversion for international customers), a message explaining why you're the right provider, and optionally your estimated pickup and delivery times.\n\nBidding tips:\n- Read the full job description before bidding. Customers notice when bids don't address their specific requirements.\n- Price competitively but don't underbid to win. Cheap bids make customers suspicious.\n- Include your relevant experience in the bid message: 'I've completed 50+ similar runs on this lane with a 98% on-time rate.'\n- Respond quickly. The first qualified bid gets more attention than the tenth.\n- Your CouthActs Score is visible on every bid. A higher score makes your bid more compelling even at a higher price." },
        { title: "Instant Jobs — How to Win Real-Time Requests", order: 6, durationMins: 15, content: "CouthActs Instant is the platform's real-time matching system for taxi rides, limousine services, and courier deliveries. When a customer posts an Instant request, you have 90 seconds to accept it — first verified provider to accept wins the job.\n\nTo receive Instant Jobs, go to /instant/provider and toggle 'Online.' While you're online, the page polls for new instant requests every 3 seconds. When a job appears, you'll see the mode, pickup location, drop-off location, and the customer's budget.\n\nWinning tips for Instant Jobs:\n- Stay online during your peak hours. The more you're available, the more requests you see.\n- Accept quickly. You have 90 seconds, but the fastest provider gets the job.\n- Only accept jobs you can actually start immediately. Instant means NOW.\n- Your CouthActs Score still matters — customers can see who accepted, and a low-score provider on an instant job still gets reviews.\n\nIf no provider accepts within 90 seconds, the customer's request automatically converts to a standard posting. The budget is refunded to their wallet (posting fee and protection fee are kept), and the job enters the regular bidding queue.\n\nInstant Jobs are a great way to build volume quickly. The jobs tend to be smaller (taxi rides, courier deliveries), but the speed means you can complete multiple jobs per day and rapidly build your CouthActs Score." },
        { title: "Getting Paid — Escrow, Wallet, and Stripe Connect", order: 7, durationMins: 15, content: "Understanding how money flows on CouthActs is critical for your business.\n\nWhen a customer posts a job, their full budget is held in their CouthActs Wallet as an escrow hold. When they accept your bid, an escrow record is created for the agreed amount. If your bid is lower than the budget, the difference is refunded to the customer immediately.\n\nThe escrow holds until BOTH parties confirm completion. The customer marks the job as done, and you mark it as done. PIN confirmation at delivery can also trigger your completion mark automatically.\n\nOnce both parties confirm, the escrow releases. The platform deducts its fee (1-8% on a sliding scale based on the job value), and the remainder is credited to your CouthActs Wallet.\n\nTo get money from your wallet to your bank account, you need Stripe Connect. Go to Settings → Stripe Connect and complete the onboarding process. Stripe will ask for your business details, bank account information, and identity verification (separate from CouthActs KYC).\n\nOnce Stripe Connect is set up, you can withdraw from your wallet at any time:\n- Standard withdrawal: free, arrives in 2-5 business days\n- Instant payout (if supported by your bank): 1.5% fee, arrives within 30 minutes\n\nMinimum withdrawal is $10. There's no CouthActs fee for standard withdrawals — only Stripe's standard transfer fees apply.\n\nFor Elite providers (CouthActs Score 90+, 50+ completed jobs), CouthActs Advance offers advance payments — you can receive 70% of the escrow amount before the job is complete, with a 2.5% advance fee." },
        { title: "Your First 30 Days — Building a 5-Star Reputation", order: 8, durationMins: 15, content: "Your first 30 days on CouthActs set the trajectory for your entire provider career. Here's the playbook:\n\nDay 1-3: Complete your profile, upload KYC verification ($20), submit business documents for KYB (if non-solopreneur), set up Stripe Connect. Don't bid on anything yet — get verified first.\n\nDay 4-7: Start with small, local jobs in your strongest mode. Your first 5 jobs should be ones you can absolutely crush — on time, great communication, no issues. These early reviews shape your score.\n\nDay 8-14: Increase volume. Bid on more jobs, respond faster. Start tracking your response time — under 1 hour is the target. Set up the availability calendar so customers can see you're active.\n\nDay 15-21: If you're in an instant-eligible mode (taxi, limo, courier), start going online for Instant Jobs during peak hours. The fast turnaround builds your job count and score quickly.\n\nDay 22-30: By now you should have 10-15 completed jobs. Review your score breakdown. Are you losing points on response time? On-time rate? Reviews? Fix the weakest area.\n\nCommunication rules:\n- Acknowledge every booking within 30 minutes\n- Send a status update before pickup\n- Notify immediately if there's any delay\n- At delivery, confirm via PIN and send a completion message\n- After completion, politely ask for a review\n\nThe providers who reach Trusted tier (75+) within their first 60 days are the ones who communicate proactively, deliver on time, and never accept jobs they can't fulfill. It's not about being the cheapest — it's about being the most reliable." },
      ],
      examQuestions: [
        { question: "What is the CouthActs Score range?", optionA: "1-10", optionB: "0-50", optionC: "0-100", optionD: "1-1000", correctAnswer: "C", explanation: "The CouthActs Score is calculated on a 0-100 point scale.", order: 1 },
        { question: "How much does identity verification (KYC) cost?", optionA: "$5", optionB: "$10", optionC: "$15", optionD: "$20", correctAnswer: "D", explanation: "KYC verification costs $20 per attempt and is non-refundable regardless of outcome.", order: 2 },
        { question: "What happens if a customer's name doesn't match their government ID?", optionA: "Auto-corrected", optionB: "Verification rejected", optionC: "Warning issued", optionD: "Partial approval", correctAnswer: "B", explanation: "Verification is rejected if the name doesn't match. The $20 fee is not refunded.", order: 3 },
        { question: "What is the minimum CouthActs Score for Elite tier?", optionA: "80", optionB: "85", optionC: "90", optionD: "95", correctAnswer: "C", explanation: "Elite tier requires a score of 90-100.", order: 4 },
        { question: "How long do providers have to accept an Instant Job?", optionA: "30 seconds", optionB: "60 seconds", optionC: "90 seconds", optionD: "120 seconds", correctAnswer: "C", explanation: "Instant Jobs have a 90-second window for provider acceptance.", order: 5 },
        { question: "What percentage of escrow can Elite providers access through CouthActs Advance?", optionA: "50%", optionB: "60%", optionC: "70%", optionD: "80%", correctAnswer: "C", explanation: "CouthActs Advance advances 70% of the escrow amount to eligible Elite providers.", order: 6 },
        { question: "What is the escrow fee for a $10,000 job?", optionA: "8%", optionB: "6%", optionC: "4%", optionD: "2%", correctAnswer: "C", explanation: "The $5,000-$50,000 bracket has a 4% escrow fee.", order: 7 },
        { question: "How many transport modes does CouthActs support?", optionA: "12", optionB: "15", optionC: "18", optionD: "20", correctAnswer: "C", explanation: "CouthActs supports 18 transport modes spanning ground, air, sea, and rail.", order: 8 },
        { question: "What happens to an Instant Job if no provider accepts within 90 seconds?", optionA: "Cancelled with full refund", optionB: "Auto-converts to standard posting", optionC: "Rebroadcast for 90 more seconds", optionD: "Customer notified to increase budget", correctAnswer: "B", explanation: "Unaccepted Instant Jobs automatically become standard postings. Budget is refunded but posting and protection fees are kept.", order: 9 },
        { question: "What is the maximum dispute penalty on CouthActs Score?", optionA: "5 points", optionB: "10 points", optionC: "15 points", optionD: "20 points", correctAnswer: "C", explanation: "Each dispute costs 5 points, with a maximum deduction of 15 points (3+ disputes).", order: 10 },
      ],
    },

    /* ═══════════════════ COURSE 2: Transport Safety ═══════════════════ */
    {
      title: "Certified Transport Safety",
      slug: "certified-transport-safety",
      description: "Master safety protocols across all transport modes. DOT, FMCSA, IMO, and FAA compliance. Required for providers handling regulated cargo.",
      whatYouLearn: ["Pre-trip and post-trip vehicle inspection protocols", "FMCSA Hours of Service compliance", "Accident prevention and emergency response", "Cargo securement standards (FMCSA 393.100)", "Weather and road hazard decision-making", "Safety documentation and reporting"],
      category: "COMPLIANCE_SAFETY" as const, priceUsd: 79, duration: "4 hours", totalLessons: 12, level: "INTERMEDIATE" as const,
      thumbnailUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80",
      lessons: [
        { title: "Safety Culture in Transportation — Why It Matters", order: 1, durationMins: 20, content: "Safety in transportation is not a checkbox — it is a culture. Every provider on CouthActs is expected to treat safety as the non-negotiable foundation of their operations.\n\nThe transportation industry accounts for a significant portion of workplace fatalities globally. In the United States alone, the Bureau of Labor Statistics reports over 2,000 transportation-related worker deaths annually. Most of these are preventable.\n\nOn CouthActs, your safety record directly impacts your CouthActs Score. Incidents, disputes related to damaged cargo, and customer complaints about unsafe driving all contribute to score deductions. Conversely, a clean safety record, proper documentation, and proactive communication about conditions build trust and win more jobs.\n\nThis course covers the foundational safety protocols that every CouthActs provider should know — regardless of transport mode. Whether you drive a taxi in Dallas or captain a cargo vessel across the Atlantic, the principles are the same: prepare, inspect, communicate, and document." },
        { title: "Pre-Trip Inspection Standards", order: 2, durationMins: 20, content: "A pre-trip inspection is the single most important safety action you take every day. Federal regulations (49 CFR 396.13) require commercial vehicle operators to inspect their vehicle before each trip.\n\nThe inspection must cover: tires (tread depth, pressure, damage), brakes (air pressure, pad wear, fluid levels), lights and signals (headlights, taillights, turn signals, hazards), mirrors and windshield (clean, unobstructed, undamaged), fluid levels (engine oil, coolant, transmission, power steering), coupling devices (fifth wheel, king pin, safety chains for doubles), and cargo securement (tie-downs, blocking, bracing per FMCSA 393.100).\n\nDocument every pre-trip inspection. On CouthActs, you can upload inspection photos as tracking checkpoints using the DOCUMENT_POD_AI layer. This creates a timestamped, geotagged record that protects you in case of disputes.\n\nNever skip a pre-trip inspection. The 15 minutes you save could cost a life, your career, and your CouthActs reputation." },
        { title: "FMCSA Hours of Service Compliance", order: 3, durationMins: 20, content: "Hours of Service (HOS) regulations exist to prevent fatigue-related accidents. If you operate a commercial motor vehicle (CMV) in the United States, these rules are federal law.\n\nKey rules for property-carrying drivers:\n- 11-Hour Driving Limit: You may drive a maximum of 11 hours after 10 consecutive hours off duty.\n- 14-Hour Window: You may not drive after the 14th consecutive hour after coming on duty, regardless of breaks.\n- 30-Minute Break: You must take a 30-minute break after 8 cumulative hours of driving.\n- 60/70-Hour Limit: You may not drive after 60 hours on duty in 7 consecutive days (or 70 hours in 8 days).\n- 34-Hour Restart: A restart of the 60/70-hour period requires 34 consecutive hours off duty.\n\nELD (Electronic Logging Device) integration is built into CouthActs. If you use an ELD, your driving time is automatically reported via the ELD_INTEGRATION tracking layer. This creates an audit trail that proves compliance.\n\nViolations of HOS regulations carry fines of $16,000+ per violation and can result in a driver being placed out of service immediately." },
        { title: "Cargo Securement — FMCSA 393.100 Standards", order: 4, durationMins: 20, content: "Improperly secured cargo kills approximately 50 people per year in the US and injures over 15,000. FMCSA 393.100 establishes the minimum standards for securing cargo on commercial vehicles.\n\nGeneral requirements:\n- Cargo must be firmly immobilized or secured.\n- Articles of cargo that are likely to roll must be restrained by chocks, wedges, a cradle, or equivalent means.\n- Cargo must be secured by tiedowns, blocking, bracing, or a combination.\n\nWorking Load Limit (WLL): The aggregate WLL of all tiedowns must be at least 50% of the weight of the cargo. For example, a 20,000 lb load requires tiedowns with a combined WLL of at least 10,000 lbs.\n\nOn CouthActs, freight and heavy haul postings include cargo weight, dimensions, and securement requirements. Always verify that your equipment matches the job requirements before bidding.\n\nDocument cargo securement with photos at pickup. Upload them as QR_PIN_CONFIRMATION or DOCUMENT_POD_AI tracking events. This protects you against damage claims and demonstrates professionalism." },
        { title: "Accident Prevention and Defensive Driving", order: 5, durationMins: 20, content: "Defensive driving is the practice of anticipating dangerous situations despite incorrect actions of others or adverse conditions. For professional drivers, it's not optional — it's the standard.\n\nThe Smith System's five keys to safe driving:\n1. Aim High in Steering — Look 15+ seconds ahead, not just at the vehicle in front of you.\n2. Get the Big Picture — Scan mirrors every 5-8 seconds. Know what's around you at all times.\n3. Keep Your Eyes Moving — Don't fixate. Stare creates fatigue and tunnel vision.\n4. Leave Yourself an Out — Maintain space cushions on all sides when possible.\n5. Make Sure They See You — Use signals, lights, horn when necessary. Make eye contact.\n\nFollowing distance: For commercial vehicles, maintain at least one second of following distance per 10 feet of vehicle length at speeds below 40 mph. Above 40 mph, add one additional second. In adverse weather, double it.\n\nSpeed management: Speed is the #1 factor in fatal crashes. On CouthActs, providers with speed-related incidents on their record receive score deductions. The MOBILE_GPS tracking layer records speed data — excessive speeds are flagged." },
        { title: "Emergency Response Procedures", order: 6, durationMins: 20, content: "When an incident occurs, your response in the first 5 minutes determines the outcome. Every CouthActs provider should have an emergency response plan.\n\nImmediate actions after any incident:\n1. Ensure personal safety first. Move to a safe position if possible.\n2. Call 911 if there are injuries or significant hazards.\n3. Activate hazard lights and set out warning devices (reflective triangles at 10, 100, and 200 feet behind the vehicle).\n4. Do not move the vehicle unless it creates an additional hazard.\n5. Document everything: photos, witness information, police report number.\n\nOn CouthActs, immediately update the booking status and create a tracking event with the note describing the situation. This triggers an alert to the customer and the CouthActs support team. Use the SOS feature for critical emergencies — it escalates to our operations team immediately.\n\nFor HAZMAT incidents, additional requirements apply: identify the material using shipping papers and placards, establish an initial isolation zone per the Emergency Response Guidebook, and notify the National Response Center (1-800-424-8802) and CHEMTREC (1-800-424-9300)." },
        { title: "Weather and Road Hazard Decision-Making", order: 7, durationMins: 20, content: "Professional drivers must make real-time decisions about weather and road conditions. The wrong decision can be fatal.\n\nRain: Hydroplaning occurs at speeds as low as 35 mph with as little as 1/12 inch of water. Reduce speed, increase following distance, avoid cruise control. On CouthActs, send a tracking update to the customer explaining any weather-related delays.\n\nSnow and Ice: Black ice is most common between 28-32°F, especially on bridges, overpasses, and shaded areas. If conditions are dangerous, pull over and wait. No CouthActs job is worth a life.\n\nFog: Use low-beam headlights (never high beams). Reduce speed and increase following distance dramatically. If visibility drops below 200 feet, consider stopping.\n\nWind: Commercial vehicles are especially vulnerable to crosswinds on open highways, bridges, and mountain passes. If sustained winds exceed 40 mph, strongly consider delaying.\n\nThe key principle: when in doubt, don't go. Pull over, communicate with the customer via the tracking system, and wait for conditions to improve. CouthActs treats weather delays as legitimate — you will not be penalized for making safe decisions. Document the conditions with photos as tracking checkpoints." },
        { title: "Maritime Safety — IMO Standards", order: 8, durationMins: 20, content: "For CouthActs maritime providers, the International Maritime Organization (IMO) standards govern safety at sea. The SOLAS (Safety of Life at Sea) convention is the most important maritime safety treaty.\n\nKey requirements for vessel operators on CouthActs:\n- Life-saving equipment: life rafts, lifejackets, and survival craft sufficient for all persons aboard.\n- Fire safety: detection systems, extinguishers, and fire plans per SOLAS Chapter II-2.\n- Navigation safety: ECDIS, radar, AIS transponder (which feeds the AIS_MARITIME tracking layer on CouthActs).\n- Communication: GMDSS equipment for distress alerting.\n- ISM Code compliance: documented safety management system.\n\nFor yacht charter providers, the applicable regulations depend on the flag state and operating waters. At minimum, ensure: valid survey certificates, adequate life-saving equipment, certified crew, and marine insurance.\n\nOn CouthActs, maritime bookings automatically select the AIS_MARITIME tracking layer. Vessel position is broadcast via AIS and displayed on the customer's tracking page in real time." },
        { title: "Aviation Safety — FAA Standards", order: 9, durationMins: 20, content: "CouthActs aviation providers — private jet, helicopter, commercial airline, and air cargo — must comply with FAA regulations (or equivalent national authority for non-US operations).\n\nKey compliance areas:\n- Pilot certification: Current and valid certificates with appropriate ratings for the aircraft and operation type.\n- Aircraft airworthiness: Valid airworthiness certificate, annual inspections, AD (Airworthiness Directive) compliance.\n- Maintenance records: Complete and current maintenance logs accessible for review.\n- 14 CFR Part 91/135: Operational rules for general aviation and on-demand air taxi operations.\n\nCouthActs aviation bookings use the FLIGHT_TRACKING layer, which integrates ADS-B transponder data to provide real-time position, altitude, speed, and heading to the customer.\n\nPre-flight requirements: weather briefing (1-800-WX-BRIEF or ForeFlight), NOTAMs check, weight and balance calculation, fuel planning with required reserves.\n\nAviation providers on CouthActs must maintain active FAA (or equivalent) certifications. Expired certifications automatically suspend your ability to bid on aviation jobs." },
        { title: "Hazardous Materials Transport", order: 10, durationMins: 20, content: "Transporting hazardous materials (HAZMAT) requires additional training, equipment, and documentation beyond standard freight. On CouthActs, HAZMAT jobs require Elite Protection tier.\n\n49 CFR 172-180 governs HAZMAT transport in the US. Key requirements:\n- HAZMAT endorsement on CDL (requires TSA background check).\n- Proper classification, packaging, marking, labeling, and placarding.\n- Shipping papers with proper shipping names, hazard classes, ID numbers, and emergency contact.\n- Emergency Response Guidebook in the vehicle.\n\nHAZMAT classes: Class 1 (Explosives), Class 2 (Gases), Class 3 (Flammable Liquids), Class 4 (Flammable Solids), Class 5 (Oxidizers), Class 6 (Poisons/Infectious), Class 7 (Radioactive), Class 8 (Corrosives), Class 9 (Miscellaneous).\n\nOn CouthActs, HAZMAT postings require the customer to specify the hazard class, UN number, and quantity. Only providers with verified HAZMAT endorsements can see and bid on these jobs.\n\nTracking for HAZMAT uses the IOT_DEVICE layer in addition to GPS, providing temperature and condition monitoring for sensitive materials." },
        { title: "Safety Documentation and Record-Keeping", order: 11, durationMins: 20, content: "Documentation is the proof that you follow safety protocols. Without records, compliance is just a claim.\n\nRequired documentation for CouthActs providers:\n- Driver qualification file: CDL, medical certificate, MVR (Motor Vehicle Record), training certificates.\n- Vehicle records: inspection reports, maintenance records, repair orders.\n- Trip records: pre-trip inspections, post-trip reports, ELD logs.\n- HAZMAT records (if applicable): training certificates, shipping papers, incident reports.\n\nOn CouthActs, tracking events serve as digital documentation. Every GPS ping, photo checkpoint, QR/PIN scan, ELD upload, and status update is timestamped and geotagged. This creates an audit trail that protects you in disputes and demonstrates professionalism to customers.\n\nBest practice: create a tracking event at each major milestone — departure, border crossing, rest stop, fuel stop, arrival. Include a brief note. This level of documentation earns 5-star reviews and builds your CouthActs Score faster than anything else." },
        { title: "Building a Safety-First Provider Business", order: 12, durationMins: 20, content: "Safety is not a cost — it's an investment that pays dividends on CouthActs and in the real world.\n\nSafety metrics that impact your CouthActs Score:\n- Zero incident record: no disputes related to damaged cargo, unsafe driving, or injuries.\n- Proactive communication: weather delays, route changes, and condition updates sent as tracking events.\n- Documentation compliance: pre-trip photos, cargo securement documentation, delivery proof.\n\nBuilding a safety culture in your operation:\n1. Training: Complete CouthActs Academy safety courses for every team member.\n2. Inspection: Never skip pre-trip. Make it a non-negotiable daily habit.\n3. Communication: Use the tracking system to keep customers informed.\n4. Documentation: Upload photos and notes at every checkpoint.\n5. Continuous improvement: Review any incidents or near-misses. Learn and prevent.\n\nProviders who complete the Certified Transport Safety course earn a certification badge on their profile. This badge is visible on every bid you submit and signals to customers that you take safety seriously.\n\nThe CouthActs Score gives safety-focused providers a competitive advantage. A provider with a 95 score and safety certification will win more jobs than a cheaper provider with a 70 score and no certifications — because customers trust the safe choice." },
      ],
      examQuestions: [
        { question: "What federal regulation governs pre-trip inspections for commercial vehicles?", optionA: "49 CFR 396.13", optionB: "49 CFR 172", optionC: "FMCSA 393.100", optionD: "14 CFR Part 91", correctAnswer: "A", explanation: "49 CFR 396.13 requires pre-trip inspections for commercial motor vehicles.", order: 1 },
        { question: "What is the maximum driving hours allowed after 10 hours off duty?", optionA: "8 hours", optionB: "10 hours", optionC: "11 hours", optionD: "14 hours", correctAnswer: "C", explanation: "The 11-Hour Driving Limit allows driving up to 11 hours after 10 consecutive hours off duty.", order: 2 },
        { question: "What is the minimum aggregate Working Load Limit for tiedowns relative to cargo weight?", optionA: "25%", optionB: "50%", optionC: "75%", optionD: "100%", correctAnswer: "B", explanation: "FMCSA 393.100 requires aggregate WLL of tiedowns to be at least 50% of cargo weight.", order: 3 },
        { question: "At what speed can hydroplaning occur?", optionA: "25 mph", optionB: "35 mph", optionC: "45 mph", optionD: "55 mph", correctAnswer: "B", explanation: "Hydroplaning can occur at speeds as low as 35 mph with as little as 1/12 inch of water.", order: 4 },
        { question: "Which tracking layer do maritime bookings use?", optionA: "MOBILE_GPS", optionB: "FLIGHT_TRACKING", optionC: "AIS_MARITIME", optionD: "SATELLITE", correctAnswer: "C", explanation: "Maritime bookings use AIS_MARITIME for vessel position tracking.", order: 5 },
        { question: "What protection tier is required for HAZMAT jobs on CouthActs?", optionA: "Basic", optionB: "Standard", optionC: "Premium", optionD: "Elite", correctAnswer: "D", explanation: "Elite Protection tier is mandatory for HAZMAT transport on CouthActs.", order: 6 },
        { question: "How many reflective triangles should be placed behind a stopped commercial vehicle?", optionA: "1", optionB: "2", optionC: "3", optionD: "4", correctAnswer: "C", explanation: "Three reflective triangles at 10, 100, and 200 feet behind the vehicle.", order: 7 },
        { question: "Which CouthActs tracking layer provides temperature monitoring for HAZMAT?", optionA: "MOBILE_GPS", optionB: "IOT_DEVICE", optionC: "SATELLITE", optionD: "BIOMETRIC", correctAnswer: "B", explanation: "IOT_DEVICE provides temperature and condition monitoring for sensitive cargo.", order: 8 },
        { question: "What IMO convention governs safety of life at sea?", optionA: "MARPOL", optionB: "SOLAS", optionC: "STCW", optionD: "ISM", correctAnswer: "B", explanation: "SOLAS (Safety of Life at Sea) is the most important maritime safety treaty.", order: 9 },
        { question: "What CouthActs feature should be used in critical emergencies?", optionA: "Tracking update", optionB: "Dispute filing", optionC: "SOS feature", optionD: "Customer message", correctAnswer: "C", explanation: "The SOS feature escalates immediately to the CouthActs operations team for critical emergencies.", order: 10 },
      ],
    },

    /* ═══════════════════ COURSE 3: Hazardous Materials ═══════════════════ */
    {
      title: "Hazardous Materials Handling",
      slug: "hazardous-materials-handling",
      description: "Comprehensive HAZMAT training covering classification, packaging, documentation, placarding, emergency response, and CouthActs-specific HAZMAT workflows.",
      whatYouLearn: ["9 HAZMAT classes and their sub-divisions", "Packaging and labeling per 49 CFR 172-180", "Proper shipping paper preparation", "Emergency response using the ERG", "CouthActs HAZMAT posting and tracking workflows", "IoT condition monitoring for regulated materials"],
      category: "COMPLIANCE_SAFETY" as const, priceUsd: 99, duration: "3 hours", totalLessons: 8, level: "ADVANCED" as const,
      thumbnailUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80",
      lessons: [
        { title: "HAZMAT Classification — The 9 Classes", order: 1, durationMins: 20, content: "The United Nations divides hazardous materials into 9 classes based on their primary hazard. Understanding classification is the foundation of safe HAZMAT transport.\n\nClass 1 — Explosives: Divided into 6 divisions (1.1 mass explosion, 1.2 projection, 1.3 fire/minor blast, 1.4 minor explosion, 1.5 blasting agents, 1.6 extremely insensitive). Examples: dynamite, ammunition, fireworks.\n\nClass 2 — Gases: Division 2.1 (flammable — propane, acetylene), 2.2 (non-flammable/non-toxic — nitrogen, CO2), 2.3 (toxic — chlorine, ammonia).\n\nClass 3 — Flammable Liquids: Flash point below 60°C. Gasoline, acetone, alcohol, diesel (though diesel is also Class 3 with higher flash point).\n\nClass 4 — Flammable Solids: 4.1 (flammable solids), 4.2 (spontaneously combustible), 4.3 (dangerous when wet — sodium, lithium).\n\nClass 5 — Oxidizers: 5.1 (oxidizers — hydrogen peroxide, potassium permanganate), 5.2 (organic peroxides).\n\nClass 6 — Toxic/Infectious: 6.1 (toxic substances — pesticides, cyanide), 6.2 (infectious substances — medical waste, cultures).\n\nClass 7 — Radioactive: Any material with specific activity greater than 70 kBq/kg.\n\nClass 8 — Corrosives: Cause visible destruction of skin or corrode steel/aluminum. Battery acid, sulfuric acid, sodium hydroxide.\n\nClass 9 — Miscellaneous: Hazards not covered by other classes. Lithium batteries, magnetized materials, dry ice, environmentally hazardous substances.\n\nOn CouthActs, HAZMAT postings require the customer to specify the class, UN number, and quantity. This information appears on the job listing so you can verify you're qualified before bidding." },
        { title: "Packaging Requirements per 49 CFR 173", order: 2, durationMins: 20, content: "Proper packaging prevents incidents during normal transport conditions — vibration, stacking, temperature changes, and loading/unloading.\n\n49 CFR 173 establishes packaging requirements. Key principles:\n\nPerformance-Oriented Packaging Standards: Packaging must pass specific tests — drop test, stacking test, internal pressure test, vibration test. Each package type has a UN specification marking (e.g., UN1A1 for steel drums, UN4G for fiberboard boxes).\n\nPacking Groups determine the degree of danger:\n- PG I: Great danger (most stringent packaging)\n- PG II: Medium danger\n- PG III: Minor danger\n\nInner vs. Outer Packaging: Many HAZMAT materials require inner packaging (bottles, cans) inside outer packaging (boxes, drums) with absorbent material or cushioning between.\n\nQuantity Limitations: Some materials have per-package quantity limits for different transport modes (passenger aircraft, cargo aircraft, vessel).\n\nOn CouthActs, when you bid on a HAZMAT job, you confirm that your packaging meets the requirements for the specified material. Failure to properly package HAZMAT material can result in fines of $500,000+ and criminal prosecution. Always verify the UN specification marking on every package before transport." },
        { title: "Shipping Papers and Documentation", order: 3, durationMins: 20, content: "Shipping papers are the critical communication link between the shipper, the carrier, and emergency responders. Without proper documentation, you cannot legally transport HAZMAT.\n\n49 CFR 172.200 requires shipping papers to include:\n1. Proper Shipping Name (from the Hazardous Materials Table)\n2. Hazard Class or Division number\n3. UN/NA Identification Number (e.g., UN1203 for gasoline)\n4. Packing Group (I, II, or III)\n5. Total quantity (weight, volume, or count)\n6. Emergency response information or reference to ERG\n7. 24-hour emergency contact phone number\n\nPlacement: Shipping papers must be within the driver's reach at all times when the vehicle is moving, and on the driver's seat or in a holder on the driver's door when the driver is not in the vehicle.\n\nOn CouthActs, HAZMAT booking details include all required shipping paper information. When you accept a HAZMAT job, verify that the physical shipping papers match the digital booking details. Any discrepancy should be reported immediately through the tracking system before departing." },
        { title: "Placarding and Marking Requirements", order: 4, durationMins: 20, content: "Placards are the diamond-shaped signs on all four sides of a transport vehicle that identify the hazard class of the cargo. They are the first thing emergency responders look at when arriving at an incident.\n\n49 CFR 172.500 governs placarding:\n- Placards must be displayed on all four sides of the vehicle (front, rear, left, right).\n- Minimum size: 250mm x 250mm (approximately 10 inches).\n- Must be readable from 50 meters (approximately 165 feet).\n- Must be maintained in a condition that the color, symbols, and text are clearly visible.\n\nTable 1 materials (always placarded regardless of quantity): Explosives 1.1-1.3, Poison Gas 2.3, Dangerous When Wet 4.3, Organic Peroxide Type B, Toxic 6.1 (PG I), and Radioactive Yellow III.\n\nTable 2 materials (placarded when quantity exceeds 1,001 lbs aggregate): All other HAZMAT classes.\n\nThe DANGEROUS placard can substitute for individual class placards when carrying mixed loads of Table 2 materials — but ONLY if each material is under 5,000 lbs.\n\nOn CouthActs, HAZMAT tracking events should include a photo of the vehicle with placards visible. This creates proof of compliance that protects you in any investigation." },
        { title: "Loading, Unloading, and Compatibility", order: 5, durationMins: 20, content: "Improper loading of HAZMAT materials has caused some of the worst transportation disasters in history. Compatibility rules exist to prevent dangerous reactions.\n\n49 CFR 177.848 — Segregation and Separation Chart: This table defines which hazard classes can be loaded together and which must be separated.\n\nKey incompatibilities:\n- Oxidizers (5.1) must never be loaded with flammable liquids (3), flammable solids (4.1), or organic peroxides (5.2).\n- Acids (8) must be separated from bases (8).\n- Poisons (6.1) must be separated from food and animal feed.\n- Radioactive (7) has specific distance requirements from all other classes.\n\nLoading procedures:\n1. Verify compatibility before loading any mixed HAZMAT.\n2. Secure all packages to prevent movement — shifting HAZMAT cargo can rupture packaging.\n3. Never stack beyond the package's stacking limit (indicated on the UN marking).\n4. Ensure adequate ventilation for toxic or flammable gases.\n5. Never use hooks, forklifts, or equipment that could puncture packaging unless specifically designed for that purpose.\n\nOn CouthActs, document loading with timestamped photos via the DOCUMENT_POD_AI tracking layer. Include photos of cargo securement and placard placement." },
        { title: "Emergency Response Guidebook (ERG)", order: 6, durationMins: 20, content: "The Emergency Response Guidebook (ERG) is published by the US DOT, Transport Canada, and Mexico's SCT. It is required to be in every vehicle transporting HAZMAT.\n\nThe ERG provides immediate response guidance for the first 15-30 minutes of a HAZMAT incident. It is NOT a substitute for professional HAZMAT response — it's the initial guide until specialists arrive.\n\nHow to use the ERG:\n1. Identify the material: Use the UN number (from shipping papers or placards) to look up the Guide Number in the yellow-bordered pages.\n2. If no UN number: Use the material name in the blue-bordered pages.\n3. If no identification possible: Use the placard's hazard class in the Table of Placards.\n4. Turn to the Guide Number (orange-bordered pages) for: potential hazards, public safety actions, emergency response procedures.\n5. Check the green-bordered pages for Initial Isolation and Protective Action Distances for highlighted materials.\n\nKey information in each guide:\n- FIRE: How it burns, what extinguishing agents to use, what NOT to do.\n- SPILL OR LEAK: Containment, cleanup, decontamination.\n- FIRST AID: Immediate medical response.\n\nOn CouthActs, if you encounter a HAZMAT emergency, use the SOS feature immediately. Include the UN number and Guide Number in your SOS message so the operations team can coordinate the appropriate response." },
        { title: "HAZMAT Tracking and IoT on CouthActs", order: 7, durationMins: 20, content: "CouthActs provides specialized tracking for HAZMAT transport through multiple layers working together.\n\nMOBILE_GPS: Standard real-time position tracking. Required for all HAZMAT transport.\n\nIOT_DEVICE: Temperature, humidity, and shock sensors for materials with condition requirements. Critical for:\n- Class 1 (Explosives): temperature monitoring to prevent detonation.\n- Class 2 (Refrigerated gases): temperature monitoring.\n- Class 5.2 (Organic peroxides): many require temperature-controlled transport.\n- Class 6.2 (Infectious substances): cold chain verification.\n\nGEOFENCE ALERTS: Automated notifications when HAZMAT shipments enter or leave defined zones. Used for:\n- Restricted areas (tunnels, densely populated zones where HAZMAT routing may be limited).\n- Customer-defined geofences around the origin and destination.\n\nSATELLITE: For HAZMAT transport through areas with limited cellular coverage (remote highways, rural areas). Ensures continuous tracking even without cell service.\n\nQR_PIN_CONFIRMATION: Cryptographic proof of handoff. Both pickup and delivery for HAZMAT require QR scan or PIN entry. This creates a tamper-proof chain of custody.\n\nDOCUMENT_POD_AI: Photo documentation at every checkpoint. For HAZMAT, include photos of: placards, shipping papers, cargo securement, temperature readings (if applicable), and delivery condition.\n\nAll tracking events for HAZMAT bookings are stored with full audit trail and are available for regulatory inspection if needed." },
        { title: "HAZMAT Certification and CouthActs Compliance", order: 8, durationMins: 20, content: "Completing this course and passing the exam earns you the CouthActs Hazardous Materials Handling certification. This certification:\n\n1. Adds a HAZMAT certification badge to your provider profile.\n2. Unlocks the ability to bid on HAZMAT postings (in addition to your HAZMAT endorsement on CDL).\n3. Contributes to your CouthActs Score through the verification bonus.\n4. Demonstrates to customers that you understand proper HAZMAT handling procedures.\n\nRemember: this CouthActs certification supplements but does not replace regulatory requirements. You still need:\n- CDL with HAZMAT endorsement (TSA background check)\n- DOT HAZMAT training per 49 CFR 172.704 (every 3 years)\n- Mode-specific certifications (IATA for air, IMDG for sea)\n\nOn CouthActs, HAZMAT jobs are tagged as requiring Elite Protection tier. This means:\n- Only verified providers with HAZMAT endorsement can bid.\n- Higher protection requirements for cargo coverage.\n- Mandatory IoT tracking for condition monitoring.\n- Full chain-of-custody documentation via tracking layers.\n\nThe CouthActs platform automatically enforces these requirements. If you're not HAZMAT-certified, you won't see HAZMAT jobs in your feed. This protects everyone — the customer, the provider, and the public." },
      ],
      examQuestions: [
        { question: "How many HAZMAT classes are there under the UN system?", optionA: "6", optionB: "7", optionC: "8", optionD: "9", correctAnswer: "D", explanation: "The UN divides hazardous materials into 9 classes.", order: 1 },
        { question: "Which Packing Group indicates the greatest danger?", optionA: "PG I", optionB: "PG II", optionC: "PG III", optionD: "PG IV", correctAnswer: "A", explanation: "Packing Group I indicates the greatest degree of danger.", order: 2 },
        { question: "What are the green-bordered pages of the ERG used for?", optionA: "Material identification", optionB: "Guide numbers", optionC: "Initial isolation distances", optionD: "First aid", correctAnswer: "C", explanation: "Green-bordered pages provide Initial Isolation and Protective Action Distances.", order: 3 },
        { question: "Which HAZMAT class must never be loaded with flammable liquids?", optionA: "Class 3", optionB: "Class 5.1 (Oxidizers)", optionC: "Class 8", optionD: "Class 9", correctAnswer: "B", explanation: "Oxidizers (5.1) must never be loaded with flammable liquids (3) due to fire/explosion risk.", order: 4 },
        { question: "What CouthActs tracking layer provides temperature monitoring for HAZMAT?", optionA: "MOBILE_GPS", optionB: "AIS_MARITIME", optionC: "IOT_DEVICE", optionD: "SATELLITE", correctAnswer: "C", explanation: "IOT_DEVICE provides temperature, humidity, and shock sensors for condition monitoring.", order: 5 },
        { question: "Where must shipping papers be placed when the driver is not in the vehicle?", optionA: "In the glove box", optionB: "On the driver's seat or door holder", optionC: "In the trailer", optionD: "In the shipping container", correctAnswer: "B", explanation: "Shipping papers must be on the driver's seat or in a holder on the driver's door.", order: 6 },
        { question: "What is the minimum size for HAZMAT placards?", optionA: "150mm x 150mm", optionB: "200mm x 200mm", optionC: "250mm x 250mm", optionD: "300mm x 300mm", correctAnswer: "C", explanation: "HAZMAT placards must be at least 250mm x 250mm (approximately 10 inches).", order: 7 },
        { question: "What protection tier does CouthActs require for HAZMAT transport?", optionA: "Basic", optionB: "Standard", optionC: "Premium", optionD: "Elite", correctAnswer: "D", explanation: "HAZMAT jobs on CouthActs require Elite Protection tier.", order: 8 },
      ],
    },

    /* ═══════════════════ COURSE 4: Customer Excellence ═══════════════════ */
    {
      title: "Customer Excellence Program",
      slug: "customer-excellence-program",
      description: "Master the communication, service delivery, and relationship management skills that turn one-time customers into repeat clients and earn 5-star reviews.",
      whatYouLearn: ["Communication protocols that earn 5-star reviews", "Proactive status updates using CouthActs tracking", "Handling complaints and service recovery", "Building a repeat customer base", "The connection between customer satisfaction and CouthActs Score", "Time management for on-time delivery"],
      category: "BUSINESS_OPERATIONS" as const, priceUsd: 39, duration: "2 hours", totalLessons: 6, level: "BEGINNER" as const,
      thumbnailUrl: "https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?w=600&q=80",
      lessons: [
        { title: "Why Customer Excellence Matters on CouthActs", order: 1, durationMins: 20, content: "Your CouthActs Score is directly shaped by customer reviews. Review Average accounts for 20 out of 100 points in the scoring algorithm. A provider with a perfect 5.0 average gets 20 points; a provider with a 3.5 average gets only 14 points. That 6-point gap can be the difference between Elite and Trusted tier.\n\nBut customer excellence is about more than scores. On CouthActs, the best providers aren't competing on price alone — they're competing on trust. A customer choosing between a $2,000 bid from a 70-score provider and a $2,200 bid from a 95-score provider will almost always pick the higher score. That 10% price premium is funded entirely by your reputation.\n\nRepeat customers are the most profitable segment on any platform. A customer who uses CouthActs for their first freight shipment and has an excellent experience will come back. They'll post bigger jobs, skip the bidding process and select you directly, and refer colleagues. One excellent customer interaction can generate thousands of dollars in future revenue.\n\nThis course teaches the specific communication, service delivery, and recovery skills that earn 5-star reviews consistently." },
        { title: "Communication Protocols for Every Job Phase", order: 2, durationMins: 20, content: "Professional communication follows a predictable pattern on CouthActs. Customers should never wonder what's happening.\n\nPhase 1 — Bidding: Your bid message is your first impression. Be specific: 'I'll pick up at your Dallas warehouse on Tuesday at 8 AM and deliver to the Houston site by 4 PM. I've completed 50+ runs on this lane with a 98% on-time rate.' Generic bids like 'I can do this job' tell the customer nothing.\n\nPhase 2 — After Acceptance: Send a message within 30 minutes of acceptance: 'Thank you for selecting me. I'll be at [pickup address] at [time] on [date]. I'll send a tracking update when I depart. My direct number is [number] for any questions.'\n\nPhase 3 — Pre-Pickup: 2 hours before pickup, send an update: 'On schedule for pickup at [time]. Currently at [location]. ETA [X] minutes.' Upload a pre-trip inspection photo as a DOCUMENT_POD_AI tracking event.\n\nPhase 4 — Pickup: At pickup, complete QR/PIN confirmation. Upload a photo of the cargo loaded and secured. Send a message: 'Cargo loaded and secured. Departing now. ETA to destination: [time].'\n\nPhase 5 — In Transit: Send tracking updates at major milestones. If there are delays (weather, traffic, mechanical), communicate immediately with the reason and revised ETA. Never let the customer discover a delay on their own.\n\nPhase 6 — Delivery: Complete QR/PIN confirmation. Upload delivery photos. Send message: 'Delivered successfully at [time]. Thank you for choosing CouthActs. If you're satisfied, I'd appreciate a review.'\n\nPhase 7 — Post-Delivery: If the customer leaves a positive review, send a thank-you. If they leave a negative review, respond professionally and address the concern." },
        { title: "Proactive Communication and the Tracking System", order: 3, durationMins: 20, content: "The CouthActs tracking system is your most powerful communication tool. Use it actively, not passively.\n\nMost providers only use MOBILE_GPS for basic location tracking. Top-rated providers use multiple tracking layers as a communication channel:\n\n1. DOCUMENT_POD_AI: Upload photos at every milestone — pre-trip inspection, cargo loading, waypoints, delivery. Each photo is timestamped and geotagged automatically. Customers love seeing proof of progress.\n\n2. QR_PIN_CONFIRMATION: Beyond the required pickup/delivery scans, use this for intermediate handoffs, border crossings, and custody changes.\n\n3. Status notes: Every tracking event can include a note. Use them: 'Passed Dallas weigh station, all clear' or 'Entering construction zone on I-35, expect 20-minute delay.'\n\nThe customer sees all of this in real-time on their tracking page. When a customer opens their tracking link and sees a steady stream of updates with photos and notes, their anxiety drops to zero. They trust you. They leave 5-star reviews. They come back.\n\nContrast this with a provider who sends GPS pings and nothing else. The customer sees a dot moving on a map with no context. They don't know if the cargo is secure, if the driver is communicating, or if there are any issues. This breeds anxiety, complaints, and 3-star reviews.\n\nThe tracking system is free to use. Every update you send costs you nothing but earns you everything." },
        { title: "Handling Complaints and Service Recovery", order: 4, durationMins: 20, content: "Things go wrong in transportation. Weather delays, mechanical issues, damaged cargo, missed deadlines. How you handle these situations determines whether you lose a customer or earn their loyalty.\n\nThe LAST framework for service recovery:\n\nL — Listen: Let the customer explain the problem fully before responding. Don't interrupt, don't make excuses. Acknowledge their frustration: 'I understand this is frustrating, and I take full responsibility.'\n\nA — Apologize: A sincere apology costs nothing. 'I'm sorry this happened. This is not the level of service I commit to.'\n\nS — Solve: Propose a concrete solution. 'I'd like to offer [X] to make this right.' This might be a partial refund, expedited re-delivery, or a discount on their next job.\n\nT — Thank: Thank them for bringing it to your attention. 'Thank you for telling me about this. It helps me improve my service.'\n\nOn CouthActs, disputes trigger an escrow freeze. If a customer files a dispute, the escrow is frozen immediately and the CouthActs team reviews the evidence. The best providers resolve issues before they become disputes — reach out to the customer proactively, offer a solution, and document everything through the tracking system.\n\nIf a dispute is filed against you, respond promptly with evidence: tracking events, photos, communication records. The CouthActs team reviews all evidence and makes a fair decision. A well-documented case almost always resolves in favor of the provider who communicated proactively." },
        { title: "Building a Repeat Customer Base", order: 5, durationMins: 20, content: "Repeat customers are the foundation of a sustainable provider business on CouthActs. Acquiring a new customer (through bidding) costs time and effort. Retaining an existing customer costs nearly nothing.\n\nStrategies for earning repeat business:\n\n1. Exceed expectations on the first job. Don't just meet the deadline — beat it. Don't just deliver — deliver and send a clean set of documentation photos. The first impression sets the bar.\n\n2. Follow up after delivery. A simple 'Thank you for the job. I'm available anytime you need this route again' keeps you top of mind.\n\n3. Be available. Set your CouthActs availability calendar so repeat customers can see when you're open for new jobs. Respond to their postings within 30 minutes.\n\n4. Price fairly for repeat customers. You don't need to undercut yourself, but a consistent, fair price builds loyalty. Customers hate price volatility.\n\n5. Remember details. If a customer always ships to the same warehouse, note the dock hours, the receiving contact, and the preferred unloading process. Mention these in your bid: 'I know your Houston warehouse receives between 7 AM and 3 PM at Dock 4.' This signals professionalism.\n\n6. Ask for reviews. After every successful delivery, ask: 'If you were satisfied with the service, I'd really appreciate a review on CouthActs. It helps me serve more customers like you.' Most satisfied customers will leave a review if asked directly." },
        { title: "Time Management and On-Time Delivery", order: 6, durationMins: 20, content: "On-Time Rate accounts for 20 points in the CouthActs Score. A provider with 100% on-time delivery earns all 20 points. A provider at 80% on-time earns 16 points. That 4-point gap compounds over time.\n\nTime management principles for transportation providers:\n\n1. Plan for the worst, aim for the best. If Google Maps says 6 hours, plan for 7.5. Factor in: traffic, weather, loading/unloading time, fuel stops, HOS-mandated breaks.\n\n2. Depart early. The single easiest way to be on time is to leave early. Build a 15-20% time buffer into every trip.\n\n3. Communicate delays immediately. If you know you'll be late, tell the customer NOW — not when you arrive late. A customer who learns about a 2-hour delay in advance adjusts their plans. A customer who discovers it at delivery time is furious.\n\n4. Track your on-time rate. Review it in your CouthActs dashboard after every completed job. If you're below 90%, analyze why: are you underestimating transit times? Accepting too-tight deadlines? Having loading/unloading delays?\n\n5. Don't accept jobs you can't deliver on time. If a customer needs delivery by Friday at noon and you know you can't make it, don't bid. Winning a job you can't fulfill on time damages your score more than not bidding at all.\n\n6. Use the CouthActs tracking system to communicate ETAs. When your tracking shows you're 30 minutes out, send a note: 'ETA 30 minutes. On schedule for delivery.' This builds confidence and earns top reviews.\n\nThe best providers on CouthActs have 95%+ on-time rates. They achieve this not by driving faster, but by planning better, communicating proactively, and never over-committing." },
      ],
      examQuestions: [
        { question: "How many CouthActs Score points does Review Average contribute?", optionA: "10 points", optionB: "15 points", optionC: "20 points", optionD: "25 points", correctAnswer: "C", explanation: "Review Average contributes 20 points to the CouthActs Score.", order: 1 },
        { question: "How soon after bid acceptance should you send a confirmation message?", optionA: "Within 1 hour", optionB: "Within 30 minutes", optionC: "Within 2 hours", optionD: "Within 24 hours", correctAnswer: "B", explanation: "Send a confirmation message within 30 minutes of acceptance.", order: 2 },
        { question: "What does the 'L' stand for in the LAST service recovery framework?", optionA: "Lead", optionB: "Listen", optionC: "Learn", optionD: "Log", correctAnswer: "B", explanation: "LAST = Listen, Apologize, Solve, Thank.", order: 3 },
        { question: "What happens when a customer files a dispute on CouthActs?", optionA: "Provider is banned", optionB: "Escrow is frozen immediately", optionC: "Payment is released", optionD: "Nothing until review", correctAnswer: "B", explanation: "When a dispute is filed, escrow is frozen immediately pending review.", order: 4 },
        { question: "How many CouthActs Score points does On-Time Rate contribute?", optionA: "10 points", optionB: "15 points", optionC: "20 points", optionD: "25 points", correctAnswer: "C", explanation: "On-Time Rate contributes 20 points to the CouthActs Score.", order: 5 },
        { question: "What tracking layer should be used for photo documentation at milestones?", optionA: "MOBILE_GPS", optionB: "IOT_DEVICE", optionC: "DOCUMENT_POD_AI", optionD: "SATELLITE", correctAnswer: "C", explanation: "DOCUMENT_POD_AI is used for photo documentation at checkpoints.", order: 6 },
      ],
    },

    /* ═══════════════════ COURSE 5: Fleet Management ═══════════════════ */
    {
      title: "Fleet Management Essentials",
      slug: "fleet-management-essentials",
      description: "Scale your transportation business on CouthActs. Learn fleet operations, driver management, route optimization, financial planning, and using the CouthActs API for automation.",
      whatYouLearn: ["Fleet maintenance scheduling and cost control", "Driver recruitment, training, and performance management", "Route optimization and fuel efficiency", "Financial planning for transportation businesses", "Using the CouthActs API for fleet automation", "Scaling from single operator to fleet owner"],
      category: "BUSINESS_OPERATIONS" as const, priceUsd: 69, duration: "3 hours", totalLessons: 8, level: "INTERMEDIATE" as const,
      thumbnailUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=600&q=80",
      lessons: [
        { title: "The Single Operator to Fleet Owner Journey", order: 1, durationMins: 20, content: "Most CouthActs providers start as single operators — one person, one vehicle, one mode. The transition from single operator to fleet owner is one of the most significant business decisions you'll make.\n\nSigns you're ready to scale:\n- You're consistently turning down jobs because you're fully booked.\n- Your CouthActs Score is 85+ and your reviews are strong.\n- You've built repeat customer relationships that generate predictable revenue.\n- You have at least 6 months of operating capital saved.\n- You understand your unit economics: cost per mile, average revenue per job, profit margin.\n\nThe scaling path on CouthActs:\n1. Single operator: You drive, you manage, you communicate. Focus on building your score and reputation.\n2. Owner-operator with 1 subcontractor: You take on a second driver for overflow. You still manage operations directly.\n3. Small fleet (2-5 vehicles): You shift from driving to managing. You need systems for dispatch, communication, and quality control.\n4. Growing fleet (5-15 vehicles): You need dedicated admin support, fleet management software, and the CouthActs API for automation.\n5. Enterprise fleet (15+): You're managing a business, not a vehicle. You need the CouthActs Enterprise API, dedicated account management, and volume-based pricing.\n\nThe key mistake most providers make: scaling too fast without systems. Adding a second vehicle before you have processes for dispatch, communication, and quality control will damage your CouthActs Score — because you can't maintain the same service quality without systems." },
        { title: "Fleet Maintenance Scheduling and Cost Control", order: 2, durationMins: 20, content: "Vehicle maintenance is your single largest operational cost after fuel. A well-maintained fleet runs efficiently, avoids breakdowns, and protects your CouthActs Score (breakdowns cause delays, which hurt your on-time rate).\n\nPreventive maintenance schedule:\n- Daily: Pre-trip inspection (lights, tires, fluids, brakes). Document with DOCUMENT_POD_AI tracking event.\n- Every 5,000-7,500 miles: Oil change, filter replacement, tire rotation.\n- Every 15,000 miles: Brake inspection, transmission service, coolant flush.\n- Every 30,000 miles: Major service — timing belt, suspension, complete fluid replacement.\n- Annual: DOT annual inspection, emission testing, registration renewal.\n\nCost control strategies:\n1. Track cost per mile for each vehicle. Divide total maintenance costs by total miles driven. Industry average for commercial trucks is $0.15-0.20/mile.\n2. Buy tires in bulk. Negotiate with tire suppliers for fleet pricing.\n3. Establish relationships with 2-3 repair shops. Volume relationships get priority scheduling and better pricing.\n4. Consider a preventive maintenance contract for larger fleets — fixed monthly cost per vehicle for all scheduled maintenance.\n5. Track fuel efficiency per vehicle. A sudden drop in MPG often indicates mechanical problems before they become breakdowns.\n\nOn CouthActs, vehicle breakdowns during active jobs must be communicated immediately to the customer via tracking updates. A proactive update like 'Mechanical issue at mile 250. Repair estimated at 2 hours. Revised ETA: 4 PM' is far better than silence." },
        { title: "Driver Recruitment and Performance Management", order: 3, durationMins: 20, content: "Your drivers ARE your business on CouthActs. Their performance directly impacts your CouthActs Score, customer reviews, and repeat business rate.\n\nRecruiting quality drivers:\n- Look for experience in your transport mode. A great freight driver may be a poor courier — different skills, different pace.\n- Verify credentials: valid CDL with appropriate endorsements, clean MVR (Motor Vehicle Record), drug test compliance.\n- Check references from previous employers. Ask specifically about: reliability, communication, customer interaction, and incident history.\n- Offer competitive compensation. The best drivers have options — underpaying ensures you get the bottom of the talent pool.\n\nPerformance management on CouthActs:\n- Each booking has tracking data. Review your drivers' tracking events: Are they sending proactive updates? Are they uploading photos at milestones? Are they on time?\n- Customer reviews mention specific drivers. Read them. A driver who consistently earns 5-star reviews with comments like 'Great communication' is worth retaining. A driver who earns 3-star reviews needs coaching or replacement.\n- Set clear standards: minimum communication frequency, mandatory photo checkpoints, response time targets.\n- Pay bonuses for high performance: on-time delivery bonus, 5-star review bonus, zero-incident bonus.\n\nOn CouthActs, your business reputation is your CouthActs Score. Every driver working under your provider account affects that score. One bad driver can destroy years of reputation in a few jobs." },
        { title: "Route Optimization and Fuel Efficiency", order: 4, durationMins: 20, content: "Fuel is typically 30-40% of a fleet's operating cost. Route optimization reduces fuel consumption, improves on-time delivery, and increases the number of jobs you can complete per day.\n\nRoute optimization principles:\n1. Plan routes before accepting bids. Know the exact distance, estimated drive time, fuel stops, and rest stops before you commit to a price and deadline.\n2. Avoid empty miles. After a delivery, check CouthActs for return-route jobs. A truck returning empty from Houston to Dallas could pick up a job going the same direction — doubling revenue with minimal additional cost.\n3. Use real-time traffic data. Google Maps is a starting point, but dedicated routing software (Samsara, KeepTruckin) provides truck-specific routing that avoids low bridges, weight-restricted roads, and construction zones.\n4. Batch deliveries when possible. Multiple smaller jobs going in the same direction can be combined if timing and cargo compatibility allow.\n\nFuel efficiency strategies:\n- Maintain optimal tire pressure. Under-inflated tires increase fuel consumption by 3-5%.\n- Use cruise control on highways. Constant speed burns less fuel than acceleration/deceleration.\n- Reduce idle time. One hour of idling burns 0.8-1.0 gallons of diesel.\n- Monitor speed. Fuel efficiency drops dramatically above 55 mph — each 5 mph above 55 costs approximately $0.10/mile more in fuel.\n\nThe CouthActs Load Board is your best tool for avoiding empty miles. After completing a delivery, browse jobs originating near your current location. This is especially effective for long-haul freight." },
        { title: "Financial Planning for Transportation Businesses", order: 5, durationMins: 20, content: "Most transportation businesses fail not because they can't find jobs — but because they can't manage cash flow. Understanding your finances is the difference between a growing fleet and a bankrupt one.\n\nKey financial metrics for CouthActs providers:\n\n1. Revenue per mile: Total revenue divided by total miles driven. Benchmark: $2.50-4.00/mile for freight trucking, varies by mode.\n2. Cost per mile: Total operating costs (fuel, maintenance, insurance, driver pay, depreciation) divided by total miles. Benchmark: $1.50-2.50/mile.\n3. Profit margin: (Revenue - Costs) / Revenue. Healthy benchmark: 15-25%.\n4. Utilization rate: Percentage of available hours that your vehicles are earning revenue. Target: 80%+ for long-haul, 60%+ for local.\n\nCouthActs-specific financial considerations:\n- Escrow fees: 1-8% on a sliding scale. For a $10,000 job in the $5K-$50K bracket, that's 4% = $400. Factor this into your bidding.\n- Posting fees: Paid by the customer, not the provider. No cost to bid.\n- CouthActs Advance: If you're Elite tier, you can access 70% of escrow early at 2.5% fee. Use this for fuel and driver pay on active jobs — but factor the 2.5% into your profitability.\n- Stripe Connect fees: Standard transfers are free from CouthActs but Stripe charges its processing fee on the transfer to your bank.\n\nCash flow management:\n- Maintain at least 60 days of operating expenses in reserve.\n- Don't take on vehicle loans that require more than 30% of your monthly revenue for payments.\n- Use CouthActs Advance strategically — it's a tool for cash flow smoothing, not a substitute for profitability." },
        { title: "Using the CouthActs API for Fleet Automation", order: 6, durationMins: 20, content: "As your fleet grows beyond 5 vehicles, manual management of CouthActs bookings becomes a bottleneck. The CouthActs Provider API enables automation.\n\nKey API capabilities for fleet operators:\n\n1. Job monitoring: GET /api/provider/v1/jobs — Programmatically query available jobs matching your fleet's modes and service areas. Filter by mode, budget range, origin, and destination. Build internal tools that alert dispatchers when high-value jobs appear.\n\n2. Booking management: GET /api/provider/v1/bookings — Monitor all active bookings across your fleet. Build dashboards showing which vehicles are on which jobs, ETAs, and delivery status.\n\n3. Tracking automation: POST /api/provider/v1/tracking — Push GPS updates programmatically. If your vehicles use fleet telematics (Samsara, Geotab, KeepTruckin), build an integration that automatically sends position data to CouthActs. Specify the tracking layer: MOBILE_GPS for standard, ELD_INTEGRATION for ELD data, IOT_DEVICE for sensor data.\n\n4. Wallet management: GET /api/provider/v1/wallet — Monitor your wallet balance and transaction history. Set up alerts when balance drops below a threshold.\n\nAPI setup:\n1. Go to Settings in your CouthActs dashboard.\n2. Generate a Provider API key (starts with ca_live_ or ca_test_).\n3. Use the key in the X-API-Key header for all requests.\n\nThe Starter API tier (free, 100 calls/day) is sufficient for small fleets. Growth tier ($299/mo, 10K calls/day) is needed for automated tracking updates. Enterprise tier (custom pricing, unlimited) is for large fleet operations." },
        { title: "Scaling Operations and Multi-Mode Expansion", order: 7, durationMins: 20, content: "Once your fleet is running efficiently in one mode, consider expanding into adjacent modes. CouthActs supports 18 modes — each one is a new revenue stream.\n\nNatural expansion paths:\n- Freight trucking → Heavy haul (requires equipment upgrade but similar skills)\n- Courier/last-mile → Moving (same local expertise, larger vehicles)\n- Taxi/limo → Medical transport (premium pricing, regulatory requirements)\n- Air cargo → Private jet charter (aviation expertise transfers)\n- Cargo ship → Yacht charter (maritime expertise transfers)\n\nExpansion checklist:\n1. Regulatory requirements: Every mode has specific licenses, registrations, and certifications. Research before investing.\n2. Equipment: Can you use existing vehicles or do you need new/different ones?\n3. Staff: Do your current drivers have the skills for the new mode, or do you need specialized operators?\n4. Insurance: Each mode has different protection requirements and costs.\n5. CouthActs setup: Register the new mode on your provider profile. Complete any additional verification required.\n\nThe advantage of multi-mode operation on CouthActs is that you see more jobs. A provider registered for freight trucking sees freight jobs. A provider registered for freight trucking AND heavy haul AND courier sees three times as many opportunities. More visibility = more bids = more revenue.\n\nHowever, don't expand into modes you can't serve well. A bad experience in a new mode damages your CouthActs Score across ALL modes — there's one score per provider, not per mode." },
        { title: "Enterprise Features and Volume Pricing", order: 8, durationMins: 20, content: "When your fleet reaches 15+ vehicles or you're completing 50+ jobs per month, you qualify for CouthActs Enterprise features.\n\nEnterprise benefits:\n- Volume-based escrow pricing: Custom escrow fee rates below the standard sliding scale. Negotiated based on your monthly volume.\n- Dedicated account manager: A single point of contact at CouthActs who understands your business, your routes, and your customers.\n- Priority support: Direct phone/email line with response times under 1 hour for critical issues.\n- Custom API integrations: Webhook notifications, custom tracking layer configurations, and bulk job creation APIs.\n- White-label tracking: Give your customers a tracking page branded with your company's look and feel, powered by CouthActs infrastructure.\n- SSO (Single Sign-On): Integrate CouthActs login with your company's identity provider.\n\nTo explore Enterprise features:\n1. Visit couthacts.com/enterprise\n2. Fill out the inquiry form with your fleet size, monthly volume, and primary modes.\n3. The enterprise team will reach out within 48 hours to discuss pricing and setup.\n\nFor government contracts, visit couthacts.com/government for specific procurement-ready features including SAM.gov integration, compliance reporting, and multi-agency coordination.\n\nThe CouthActs Enterprise tier is designed for providers who treat CouthActs as core infrastructure — not just a job board, but the operating system for their transportation business." },
      ],
      examQuestions: [
        { question: "What CouthActs Score is recommended before scaling to a fleet?", optionA: "70+", optionB: "75+", optionC: "80+", optionD: "85+", correctAnswer: "D", explanation: "A score of 85+ indicates you've built a strong foundation before scaling.", order: 1 },
        { question: "What is the industry benchmark cost per mile for commercial trucks?", optionA: "$0.50-1.00", optionB: "$1.00-1.50", optionC: "$1.50-2.50", optionD: "$3.00-4.00", correctAnswer: "C", explanation: "Industry benchmark operating cost is $1.50-2.50 per mile for commercial trucks.", order: 2 },
        { question: "What API endpoint is used for fleet tracking automation?", optionA: "POST /api/v1/jobs", optionB: "POST /api/provider/v1/tracking", optionC: "GET /api/track/{code}", optionD: "POST /api/tracking", correctAnswer: "B", explanation: "POST /api/provider/v1/tracking is the Provider API endpoint for pushing tracking updates.", order: 3 },
        { question: "How many days of operating expenses should a fleet maintain in reserve?", optionA: "30 days", optionB: "45 days", optionC: "60 days", optionD: "90 days", correctAnswer: "C", explanation: "Maintain at least 60 days of operating expenses in reserve for cash flow management.", order: 4 },
        { question: "What is the target vehicle utilization rate for long-haul operations?", optionA: "60%+", optionB: "70%+", optionC: "80%+", optionD: "90%+", correctAnswer: "C", explanation: "Target utilization rate is 80%+ for long-haul operations.", order: 5 },
        { question: "What monthly job volume qualifies for CouthActs Enterprise?", optionA: "20+ jobs", optionB: "30+ jobs", optionC: "40+ jobs", optionD: "50+ jobs", correctAnswer: "D", explanation: "Enterprise features are available for providers completing 50+ jobs per month.", order: 6 },
        { question: "How much fuel does one hour of idling burn (diesel)?", optionA: "0.3-0.5 gallons", optionB: "0.5-0.7 gallons", optionC: "0.8-1.0 gallons", optionD: "1.2-1.5 gallons", correctAnswer: "C", explanation: "One hour of idling burns approximately 0.8-1.0 gallons of diesel.", order: 7 },
        { question: "What is the CouthActs Provider API key prefix for live keys?", optionA: "ca_test_", optionB: "ca_live_", optionC: "ca_prod_", optionD: "ca_api_", correctAnswer: "B", explanation: "Live API keys start with ca_live_ prefix.", order: 8 },
      ],
    },
  ];

  // Seed courses
  for (const courseData of courses) {
    const course = await db.course.create({
      data: {
        title: courseData.title, slug: courseData.slug, description: courseData.description,
        whatYouLearn: courseData.whatYouLearn, category: courseData.category,
        priceUsd: courseData.priceUsd, duration: courseData.duration,
        totalLessons: courseData.totalLessons, level: courseData.level,
        thumbnailUrl: courseData.thumbnailUrl,
        isPublished: true,
      },
    });

    for (const lesson of courseData.lessons) {
      await db.lesson.create({
        data: { courseId: course.id, ...lesson },
      });
    }

    for (const q of courseData.examQuestions) {
      await db.examQuestion.create({
        data: { courseId: course.id, ...q },
      });
    }
  }

  return NextResponse.json({ message: `${courses.length} courses seeded successfully` });
}
