import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { NextResponse } from "next/server";

/**
 * POST /api/academy/seed — Admin-only. Seeds courses with content.
 */
export async function POST() {
  const session = await getSession();
  if (!session || session.user.role !== "ADMIN") {
    return NextResponse.json({ error: "Admin only" }, { status: 403 });
  }

  // Check if already seeded
  const existing = await db.course.count();
  if (existing > 0) return NextResponse.json({ message: `${existing} courses already exist. Delete first to re-seed.` });

  const courses = [
    {
      title: "Getting Started as a CouthActs Provider",
      slug: "getting-started-provider",
      description: "Learn how the CouthActs platform works, set up your provider profile, get verified, and land your first jobs.",
      whatYouLearn: ["How the platform connects providers and customers", "Setting up a profile that wins jobs", "KYC and KYB verification process", "Understanding the CouthActs Score", "Bidding strategy for new providers", "Getting paid through escrow"],
      category: "PLATFORM_MASTERY" as const, priceUsd: 49, duration: "2 hours", totalLessons: 8, level: "BEGINNER" as const,
      lessons: [
        { title: "Welcome to CouthActs — How the Platform Works", order: 1, durationMins: 15, content: "CouthActs is a global transportation infrastructure platform that connects customers who need to move people or goods with verified transportation providers. Unlike traditional freight brokers or ride-hailing apps, CouthActs supports 18 different transport modes — from taxi rides and courier deliveries to cargo ships and private jets.\n\nThe platform operates on a simple cycle: customers post transportation needs, verified providers bid on those jobs, the customer selects a provider, funds are held in escrow, the job is completed with real-time tracking, and payment is released upon mutual confirmation.\n\nEvery transaction on CouthActs is escrow-protected. When a customer posts a job, their budget is held in their CouthActs Wallet. When they accept your bid, those funds are locked in escrow. You only get paid when both you and the customer confirm the job is complete. This protects both parties — the customer knows their money is safe, and you know the funds are already committed.\n\nAs a provider, your reputation is measured by your CouthActs Score — a 0-100 rating that considers your completion rate, on-time delivery, customer reviews, response time, and dispute history. A higher score means more trust, more bid acceptances, and access to premium features like CouthActs Advance.\n\nThe platform charges a sliding escrow fee (1-8% depending on job value) which is deducted from your payout on completion. There are no upfront fees to bid on jobs. Your earnings go directly to your CouthActs Wallet, and you can withdraw to your bank account via Stripe Connect at any time." },
        { title: "Setting Up Your Provider Profile for Maximum Visibility", order: 2, durationMins: 15, content: "Your provider profile is your storefront on CouthActs. Customers see it before they accept your bid. A complete, professional profile dramatically increases your bid acceptance rate.\n\nStart with your business name. If you're a solopreneur (taxi, limo, courier, or medical transport), your business name is automatically set to your personal name. For all other modes, you'll need a registered business name with proper documentation.\n\nSelect your transport modes carefully. Only choose modes you're actually equipped and licensed to serve. A freight trucking company shouldn't select yacht charter. The platform uses your registered modes to show you relevant jobs — selecting modes you can't serve wastes everyone's time and damages your score.\n\nYour bio should be concise and professional. Lead with your experience: 'Licensed FMCSA carrier with 12 years of cross-country freight experience. 48-foot flatbed fleet specializing in construction materials.' Customers want competence, not marketing fluff.\n\nAdd your service areas — the regions where you operate. Be specific: 'Northeast US (NY, NJ, CT, PA, MA)' is better than 'United States.' Upload fleet photos if you have them — real photos of your actual vehicles, not stock images. This builds trust instantly.\n\nList your certifications: HAZMAT endorsement, TWIC card, TSA-approved, ISO certifications, protection coverage levels. Every certification you add makes your profile more credible and opens you to jobs that require those qualifications." },
        { title: "Getting Verified — KYC and KYB Explained", order: 3, durationMins: 15, content: "Identity verification is mandatory on CouthActs. You cannot bid on any job until your identity is verified. This protects both you and your customers.\n\nKYC (Know Your Customer) is personal identity verification. Every user — customer or provider — must complete KYC before accessing platform features. The process uses Persona, a government-grade identity verification service. You'll upload a photo of your government-issued ID (passport, driver's license, or national ID) and take a selfie. Persona verifies that the ID is authentic, not expired, and that the selfie matches the ID photo.\n\nCritical requirement: the first and last name on your CouthActs account must exactly match the name on your government ID. If there's a mismatch, verification will be rejected. The $20 verification fee is non-refundable regardless of outcome, so make sure your name is correct before submitting.\n\nKYB (Know Your Business) is required for non-solopreneur providers. After completing KYC, you'll need to submit your business documentation: business license, protection certificate, and any mode-specific registrations (DOT number for trucking, IMO number for maritime, FAA certificates for aviation, etc.).\n\nThe CouthActs team manually reviews business documents within 1-3 business days. Once approved, your profile shows a 'KYB Verified' badge, which significantly increases customer trust in your bids.\n\nIf you change your name on CouthActs, your verification resets and you'll need to reverify ($20 again). This prevents identity fraud." },
        { title: "Understanding the CouthActs Score", order: 4, durationMins: 15, content: "Your CouthActs Score is the single most important number on your profile. It determines your tier (Elite, Trusted, Established, or Probation), affects how customers perceive your bids, and gates access to features like CouthActs Advance.\n\nThe score is calculated on a 100-point scale with seven factors:\n\n1. Completion Rate (25 points): What percentage of accepted bookings do you complete? Cancellations hurt this metric. If you accept a job, complete it.\n\n2. On-Time Rate (20 points): Of completed jobs with a delivery deadline, what percentage arrived on or before the deadline? Late deliveries reduce this score.\n\n3. Review Average (20 points): Your average customer rating out of 5 stars, scaled to 20 points. A 4.5/5 average gives you 18/20 points.\n\n4. Response Time (10 points): How quickly do you respond to job opportunities? Under 1 hour = full points. Over 24 hours = zero points.\n\n5. Dispute Penalty (-5 per dispute, max -15): Each dispute filed against you in the last 12 months costs 5 points. Three or more disputes deducts the maximum 15 points.\n\n6. Account Age (max 10 points): 1 point per month you've been on the platform, up to 10 points. Longevity builds trust.\n\n7. Verification Bonus (15 points): Being fully verified (KYC + KYB approved) adds 15 points.\n\nTier thresholds: 90-100 = Elite (gold), 75-89 = Trusted (silver), 60-74 = Established (gray), below 60 = Probation (red).\n\nYour score recalculates after every completed job. Focus on completing jobs, delivering on time, and communicating well — the score follows naturally." },
        { title: "How to Find and Bid on Jobs", order: 5, durationMins: 15, content: "Jobs on CouthActs come to you in two ways: the Browse Jobs page and Instant Jobs.\n\nThe Browse Jobs page shows all open postings that match your registered transport modes. If you're registered for FREIGHT_TRUCKING and HEAVY_HAUL, you'll only see freight and heavy haul jobs. You won't see taxi requests or yacht charters. This ensures every job you see is relevant to your capabilities.\n\nFor freight and cargo providers, the Load Board is your primary tool. It filters specifically for trucking, heavy haul, hazmat, oversized, rail, air cargo, and ocean freight. You can filter by mode, sort by budget or pickup date, and toggle for hazmat-only or fresh-in-the-last-24-hours jobs.\n\nWhen you find a job you want, click it to see full details: route, cargo specs, dates, insurance requirements, and the customer's budget range. Then click 'Place Bid' in the sidebar.\n\nYour bid should include: your price (in USD — the platform handles currency conversion for international customers), a message explaining why you're the right provider, and optionally your estimated pickup and delivery times.\n\nBidding tips:\n- Read the full job description before bidding. Customers notice when bids don't address their specific requirements.\n- Price competitively but don't underbid to win. Cheap bids make customers suspicious.\n- Include your relevant experience in the bid message: 'I've completed 50+ similar runs on this lane with a 98% on-time rate.'\n- Respond quickly. The first qualified bid gets more attention than the tenth.\n- Your CouthActs Score is visible on every bid. A higher score makes your bid more compelling even at a higher price." },
        { title: "Instant Jobs — How to Win Real-Time Requests", order: 6, durationMins: 15, content: "CouthActs Instant is the platform's real-time matching system for taxi rides, limousine services, and courier deliveries. When a customer posts an Instant request, you have 90 seconds to accept it — first verified provider to accept wins the job.\n\nTo receive Instant Jobs, go to /instant/provider and toggle 'Online.' While you're online, the page polls for new instant requests every 3 seconds. When a job appears, you'll see the mode, pickup location, drop-off location, and the customer's budget.\n\nWinning tips for Instant Jobs:\n- Stay online during your peak hours. The more you're available, the more requests you see.\n- Accept quickly. You have 90 seconds, but the fastest provider gets the job.\n- Only accept jobs you can actually start immediately. Instant means NOW.\n- Your CouthActs Score still matters — customers can see who accepted, and a low-score provider on an instant job still gets reviews.\n\nIf no provider accepts within 90 seconds, the customer's request automatically converts to a standard posting. The budget is refunded to their wallet (posting fee and protection fee are kept), and the job enters the regular bidding queue.\n\nInstant Jobs are a great way to build volume quickly. The jobs tend to be smaller (taxi rides, courier deliveries), but the speed means you can complete multiple jobs per day and rapidly build your CouthActs Score." },
        { title: "Getting Paid — Escrow, Wallet, and Stripe Connect", order: 7, durationMins: 15, content: "Understanding how money flows on CouthActs is critical for your business.\n\nWhen a customer posts a job, their full budget is held in their CouthActs Wallet as an escrow hold. When they accept your bid, an escrow record is created for the agreed amount. If your bid is lower than the budget, the difference is refunded to the customer immediately.\n\nThe escrow holds until BOTH parties confirm completion. The customer marks the job as done, and you mark it as done. PIN confirmation at delivery can also trigger your completion mark automatically.\n\nOnce both parties confirm, the escrow releases. The platform deducts its fee (1-8% on a sliding scale based on the job value), and the remainder is credited to your CouthActs Wallet.\n\nTo get money from your wallet to your bank account, you need Stripe Connect. Go to Settings → Stripe Connect and complete the onboarding process. Stripe will ask for your business details, bank account information, and identity verification (separate from CouthActs KYC).\n\nOnce Stripe Connect is set up, you can withdraw from your wallet at any time:\n- Standard withdrawal: free, arrives in 2-5 business days\n- Instant payout (if supported by your bank): 1.5% fee, arrives within 30 minutes\n\nMinimum withdrawal is $10. There's no CouthActs fee for standard withdrawals — only Stripe's standard transfer fees apply.\n\nFor Elite providers (CouthActs Score 90+, 50+ completed jobs), CouthActs Advance offers advance payments — you can receive 70% of the escrow amount before the job is complete, with a 2.5% advance fee." },
        { title: "Your First 30 Days — Building a 5-Star Reputation", order: 8, durationMins: 15, content: "Your first 30 days on CouthActs set the trajectory for your entire provider career. Here's the playbook:\n\nDay 1-3: Complete your profile, upload KYC verification ($20), submit business documents for KYB (if non-solopreneur), set up Stripe Connect. Don't bid on anything yet — get verified first.\n\nDay 4-7: Start with small, local jobs in your strongest mode. Your first 5 jobs should be ones you can absolutely crush — on time, great communication, no issues. These early reviews shape your score.\n\nDay 8-14: Increase volume. Bid on more jobs, respond faster. Start tracking your response time — under 1 hour is the target. Set up the availability calendar so customers can see you're active.\n\nDay 15-21: If you're in an instant-eligible mode (taxi, limo, courier), start going online for Instant Jobs during peak hours. The fast turnaround builds your job count and score quickly.\n\nDay 22-30: By now you should have 10-15 completed jobs. Review your score breakdown. Are you losing points on response time? On-time rate? Reviews? Fix the weakest area.\n\nCommunication rules:\n- Acknowledge every booking within 30 minutes\n- Send a status update before pickup\n- Notify immediately if there's any delay\n- At delivery, confirm via PIN and send a completion message\n- After completion, politely ask for a review\n\nThe providers who reach Trusted tier (75+) within their first 60 days are the ones who communicate proactively, deliver on time, and never accept jobs they can't fulfill. It's not about being the cheapest — it's about being the most reliable." },
      ],
      examQuestions: [
        { question: "What is the CouthActs Score range?", optionA: "1-10", optionB: "0-50", optionC: "0-100", optionD: "1-1000", correctAnswer: "C", explanation: "The CouthActs Score is calculated on a 0-100 point scale.", order: 1 },
        { question: "How much does identity verification (KYC) cost?", optionA: "$5", optionB: "$10", optionC: "$15", optionD: "$20", correctAnswer: "D", explanation: "KYC verification costs $20 per attempt and is non-refundable regardless of outcome.", order: 2 },
        { question: "What happens if a customer's name doesn't match their government ID?", optionA: "Auto-corrected", optionB: "Verification rejected", optionC: "Warning issued", optionD: "Partial approval", correctAnswer: "B", explanation: "Verification is rejected if the name doesn't match. The $20 fee is not refunded.", order: 3 },
        { question: "What is the minimum CouthActs Score for Elite tier?", optionA: "80", optionB: "85", optionC: "90", optionD: "95", correctAnswer: "C", explanation: "Elite tier requires a score of 90-100.", order: 4 },
        { question: "How long do providers have to accept an Instant Job?", optionA: "30 seconds", optionB: "60 seconds", optionC: "90 seconds", optionD: "120 seconds", correctAnswer: "C", explanation: "Instant Jobs have a 90-second window for provider acceptance.", order: 5 },
        { question: "What percentage of escrow can Elite providers access through CouthActs Advance?", optionA: "50%", optionB: "60%", optionC: "70%", optionD: "80%", correctAnswer: "C", explanation: "CouthActs Advance advances 70% of the escrow amount to eligible Elite providers.", order: 6 },
        { question: "What is the escrow fee for a $10,000 job?", optionA: "8%", optionB: "6%", optionC: "4%", optionD: "2%", correctAnswer: "C", explanation: "The $5,000-$50,000 bracket has a 4% escrow fee.", order: 7 },
        { question: "How many transport modes does CouthActs support?", optionA: "12", optionB: "15", optionC: "18", optionD: "20", correctAnswer: "C", explanation: "CouthActs supports 18 transport modes spanning ground, air, sea, and rail.", order: 8 },
        { question: "What happens to an Instant Job if no provider accepts within 90 seconds?", optionA: "Cancelled with full refund", optionB: "Auto-converts to standard posting", optionC: "Rebroadcast for 90 more seconds", optionD: "Customer notified to increase budget", correctAnswer: "B", explanation: "Unaccepted Instant Jobs automatically become standard postings. Budget is refunded but posting and protection fees are kept.", order: 9 },
        { question: "What is the maximum dispute penalty on CouthActs Score?", optionA: "5 points", optionB: "10 points", optionC: "15 points", optionD: "20 points", correctAnswer: "C", explanation: "Each dispute costs 5 points, with a maximum deduction of 15 points (3+ disputes).", order: 10 },
        { question: "What verification is required for a solopreneur taxi provider?", optionA: "KYC only", optionB: "KYC + KYB", optionC: "KYB only", optionD: "No verification needed", correctAnswer: "A", explanation: "Solopreneurs (taxi, limo, courier, medical) require only KYC personal identity verification. KYB is for business entities.", order: 11 },
        { question: "What is the minimum withdrawal amount for provider payouts?", optionA: "$1", optionB: "$5", optionC: "$10", optionD: "$25", correctAnswer: "C", explanation: "The minimum withdrawal from CouthActs Wallet to a bank account is $10.", order: 12 },
        { question: "How many points does account verification add to your CouthActs Score?", optionA: "5", optionB: "10", optionC: "15", optionD: "20", correctAnswer: "C", explanation: "Being fully verified (KYC + KYB approved) adds 15 bonus points to the CouthActs Score.", order: 13 },
        { question: "Which scoring factor has the highest weight in the CouthActs Score?", optionA: "On-time rate", optionB: "Completion rate", optionC: "Review average", optionD: "Response time", correctAnswer: "B", explanation: "Completion rate carries the highest weight at 25 points out of 100.", order: 14 },
        { question: "What is the posting fee minimum for any transport mode?", optionA: "$1", optionB: "$2", optionC: "$5", optionD: "$10", correctAnswer: "B", explanation: "The absolute minimum posting fee is $2 regardless of mode or budget.", order: 15 },
        { question: "Who can see your CouthActs Score?", optionA: "Only you", optionB: "Only customers", optionC: "Everyone on the platform", optionD: "Only admin", correctAnswer: "C", explanation: "CouthActs Score is visible to all platform users — it appears on your profile and every bid you submit.", order: 16 },
        { question: "What is the CouthActs Advance advance fee?", optionA: "1%", optionB: "1.5%", optionC: "2%", optionD: "2.5%", correctAnswer: "D", explanation: "CouthActs Advance charges a 2.5% fee on the advance amount.", order: 17 },
        { question: "When is the escrow released to the provider?", optionA: "When provider marks complete", optionB: "When customer marks complete", optionC: "When both parties confirm", optionD: "Automatically after 24 hours", correctAnswer: "C", explanation: "Escrow is released only when both the customer and provider confirm job completion.", order: 18 },
        { question: "What happens to provider's CouthActs Score when a booking is completed?", optionA: "Nothing", optionB: "Automatically increases by 1", optionC: "Recalculated based on all factors", optionD: "Only changes if review is left", correctAnswer: "C", explanation: "The CouthActs Score is fully recalculated after every completed booking, considering all seven factors.", order: 19 },
        { question: "What protection tier is required for HAZMAT transport?", optionA: "Basic", optionB: "Standard", optionC: "Premium", optionD: "Elite", correctAnswer: "D", explanation: "Elite Protection is mandatory for hazmat, oversized, heavy haul, armored, medical, private jet, and yacht charter jobs.", order: 20 },
      ],
    },
  ];

  // Seed courses
  for (const courseData of courses) {
    const course = await db.course.create({
      data: {
        title: courseData.title, slug: courseData.slug, description: courseData.description,
        whatYouLearn: courseData.whatYouLearn, category: courseData.category,
        priceUsd: courseData.priceUsd, duration: courseData.duration,
        totalLessons: courseData.totalLessons, level: courseData.level,
      },
    });

    for (const lesson of courseData.lessons) {
      await db.lesson.create({
        data: { courseId: course.id, ...lesson },
      });
    }

    for (const q of courseData.examQuestions) {
      await db.examQuestion.create({
        data: { courseId: course.id, ...q },
      });
    }
  }

  return NextResponse.json({ message: `${courses.length} courses seeded successfully` });
}
